server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: xin.nimil.minxin.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: xin.nimil.minxin.utils.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
  params: count=countSql

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.115.216.74:3306/minxin?userUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: Lm352385703!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    - 114.115.216.74:22122
